matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.3

language: node_js

before_script:
- yarn add global gulp-cli@1.2.2
- yarn add global gulpjs/gulp#4.0
- yarn add global node-sass
- yarn install

script:
- yarn lint
- yarn build

node_js:
- '7'

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install libx11-dev libxext-dev libxss-dev
  libxkbfile-dev; fi

cache: yarn

notifications:
  email: false
  slack:
    secure: YvaNZUBghprsoVNWkYdId/SLr/2CY44jIn2Yd9yCfPWsdX1mC/A3LM/ym+kOIxfUvnUmaYZEeyC22Z3fd8lBWkeXumT+zDfPOyj9IIMqevkXk0tc/c9ySfPvH3E9ZEoqKFhERHEigGuQ+/jDIGrL0uHoyyWG7gBhcGZzcZ2UBiB2DjPB3PTfbOlrH3xInYaUVndGpDq5AJNg8ZfW4r7JnYejyMGd4WbynpV6phYAYYVCZx0sHhfVEmcCGs1i+RL7kqPYN877QeCdLc2TEDnYLkdzejGAHY6nHrDOzXmUyKk/xWs/D9upmsh48hNGOdlARUPpif3HGaPls1KEscaIUsg9E3q4Nsw/Wa9V7X+dactoM/WwJttm4pCDpRmjkzM2Fipd8sZkslm9ou98iBLOW7t7VPYKy7MwlnSFiXSGE2du3kkLTvujBANWC7vP2haKIWpofLjALMpMTupNmVeR5VmESPpeZ10Yg0X9DkhYBJkcq0m16gO+nuxqIoGuaK3q6xSPP6pXCEEOLz4hotVpg3teUYL+rPnDEhvgwjHaBBRhhl5/vkTgJaqYuvmPIlaD6cOIqmToReaPYc54nEkygn02REQY1yeAoQSmkH6Ko6KFQum8hFBMt1R/qndksBcV+T9ZOKdSbOLoZ+ZZzUsS8SheVna5ITRcsWNIV0cbAk4=

deploy:
  provider: s3
  access_key_id: AKIAIBXD77AXW62WB2NA
  secret_access_key:
    secure: rOHS2plE+WXVJuTDt8sy8jTo877HRA7XbiNwFwfkhiZ5qYP90QFnbEkVOvsXrarDSAx9LrAPetcq4bitI+/8zlOfxA5++rw+dLpim3GJF9nhqlaFZtC0+LazbJt0Ra5oDymVT9KsdmGWpDIWwGdngZ5mgN0CZv2Xo9fKCk/Ro6qONIUo6rRUpE5hfQR2F218o8mcFcGsSh0da/keHI/ahCkvKwgSr9gZMsmreoT8OpYj5wAnPAgOiN5NnRNzROwgb6fDdLqtzArM7hvIyE56d303fpg78nyYfc+BKuXAU3yfP4KHL5RplZt7n9DqXbO0MAiJnGHGCPCLbGSF2vsqZ+axlcfzms9qYVZuub904NDkMyrB27J9EMZwvMJVo5QjoNAJ4spoZ2meu0gj9Ub5dSxPy+ihaD/VAP3Gf7m98WS16jlzq8VLSw2560NezCjirnEDKLDrBmrpa+k3go04ZFfcA9T7dGAFDADRwzue2t4IXXITIrAilh+jf6a7kATXPFc8Rl5gsjmO0ItgnObrVht0v33G9csknmnpFn/i3MVHmZtdesR97zfoQlM2Rc6qCrqNhB7oL4A38l1h11BXcGQI2q4UJwWJ+6PYlhJOUQSbONMZAv3reVTvnKLacavzTDVZKZyNNhq9NnbBFgLrKRm1BFpE5V9xzbaHm0m60dI=
  bucket: franz-travis
  region: eu-central-1
  local_dir: out
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true

env:
  global:
  - secure: nt4TlEsaqvoiHutHRDnrdVtQYTrdMpXLYwOzU1CPECjwHexPwdhri5Pa2bkIgi6lXoT2BVhaHsCWQ+50wic9ISZ7+3wjkaY3bwGvabmIFMlHUrYMIbcRYwOWZlprYIPse9IhEwSMg8qUJgAQD4uADfv8dWI3WQC3gTUsA3kxWzKbq07AQhR2azanCVZ4nvYK1HJLXhxf4r0p6LRyC94joPx/6UKBCdiUZqTHBr+9dg7HJ0Bzk8/VWuYO0PTUXxbRq0IMCUBeEgmwdB1zxMt/acumpciFk2p6aEwwkFAJ4I1FCnWe9lUNYlFmJs2Cn+4wtGlooibxWukquQY8M9+1qZKjDp/H2tY77vgRKpJ/2s9nLigy2spGR92Qk0rmnI2LwWAwKrsqsbxYZU3P9h0JllfV1jkdHJu3Yztg+kv7Kg9FnN4giE/jhZRWj0poJB3bZGVgrw+jNXl5WT544992+tUuf3W378eaKiqrtN9z6EjsbmcmRzYDpE3kkgloRA/TsFTbHNdIkUGhVGGxYa2lgFeXv5XtKdQMZW0ALySIQgvm19E6Dxfigid3IkfsPT9jv0RYQ2BTYFWb4rTnpYrMJ7H3VjcTgOGd+vpLA+ql/rzlWE+EF1tLSNQIOa8BZ94ndJzKg9cyFyNRsL1hoNMjqjKT1S48jCaXymZyNE/V/5Q=
  - secure: Yhb98CKzC81ePmFt4FH3/7ea/SXzN8M1qh5wSFy0gAsAc1r2RJHGsJdDZhlAIVxjn9CGBqkUoe2usHeQkUs4ndBxxo3U/uMR6jSbExAIvKKmNBqQLGuJXrcZFIrQz8XKznWZ7H2fq9aj3IqjIF8xpNLwyOoGzNOLVT5SnsTQsVd0lroj7uKPVfSf8QMM/33dAkkIUCCK1TTWzqw/Qz14pbekfGFiyUqFJ9KCCnPsW81p7BFUmu3JA/Vai8Mcw0go87LxQn7Q29G3CEELvLyo0v48gBgQ+ND5rkSOjdd28I6z5RvEHky35jdREPDC3qTDy9Z+q6gSqluHOz3kuPhqi/+TZJe2Uw2h472FOMeRIaKrChFjrT1HM977Uns6RErOrvoOy2hIU9i2TB2aL1as9k2T60RByojVw5yG+97O1yhe/YJtQlyu3BZPuMt6h1VyXcEJt/H8vwks8gNzdHOIIZ9Gfr/gZqFmQnS1li3MLRuJSP4Sp6hgPca9lDFhwRoSX2COD648Ur0bGce+bHzFjLEqdai/ypxOxVHZMdQSjz6/DX4ke1HVgpSCAjIxdBiCQFXarlGOt4PbljB0pTzFoX7Ufck3/umfoO0N8xpoVNAA+GY382PkD4VWLDo7kDadNvzkTVZe8dCxu+svctS9wiz7hA0I8YjF3otpoMPQIQk=
  - secure: v891R8OH/Txvr1m58nOFypjg/wQZnyW3rmmPw8KDwS3UL6fcke4wHgc8+4bnsJB2epae2A0u65GF3BPWKAM3Yxe3gtGrgCT+Sq9z0zeCBGbz+EUs7KmaOw5ra3ZpPhCEjo/swNqDlbzDy5a6oEXmKlrTpyPGXq4HjmK7PwkroV33ufIi96TcyljrwPatrv3DynEuv4rATFu+eDO9q58/vDrvW2tNJOOXbnfBgmJ1C+/LYP+U2BxTdZ8R+yLJXxFo5OGuGMBMehKqNrvIUoP8Eif0zr5D1ZiFrEwHgjffnUILD6JJJUP4eUanIABSkkHr056GZW68MVFIAmkyzTnkV6FXJOkTaUOwEnbcQfC2+oF77KQi0xVQi9WVcCfdfG21v6PWQbCuvqzPu5m8LMU7k2eJPqa9gz5+sg4Pd1Of/PpzXmkcsMeWCQdqGS2IjdcE7kaWdGAML0PYMbFTPOqTmQPMygEhoWkiiwx/R4wNOjaLjwmZ5GK8zblvsTkyhYwH8t52vH/Vm7bSvpU4zn6Of0d8pzP2tuk3iOYXD+WdC8vdNN81FTjAeD5q8J2veGqH0wOhVJfFvK7Y9b7tZpXrTk+pT0B21HPy23CkAr5StqxeQgNvwS1MUNUpUoGiVjH4gWEpDhTeQFKs7GsVc0TxdluP8MQ9VDZfMbw4PnPvYG4=
