language: node_js

before_script:
- yarn add global gulp-cli@1.2.2
- yarn add global gulpjs/gulp#4.0
- yarn add global node-sass
- yarn install

script:
- yarn lint
- yarn build

node_js:
- '7'

matrix:
  include:
  - os: linux
    sudo: required
  - os: osx
    osx_image: xcode8.3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install libx11-dev libxext-dev libxss-dev
  libxkbfile-dev; fi

cache: yarn

notifications:
  email: false
  slack:
    secure: YvaNZUBghprsoVNWkYdId/SLr/2CY44jIn2Yd9yCfPWsdX1mC/A3LM/ym+kOIxfUvnUmaYZEeyC22Z3fd8lBWkeXumT+zDfPOyj9IIMqevkXk0tc/c9ySfPvH3E9ZEoqKFhERHEigGuQ+/jDIGrL0uHoyyWG7gBhcGZzcZ2UBiB2DjPB3PTfbOlrH3xInYaUVndGpDq5AJNg8ZfW4r7JnYejyMGd4WbynpV6phYAYYVCZx0sHhfVEmcCGs1i+RL7kqPYN877QeCdLc2TEDnYLkdzejGAHY6nHrDOzXmUyKk/xWs/D9upmsh48hNGOdlARUPpif3HGaPls1KEscaIUsg9E3q4Nsw/Wa9V7X+dactoM/WwJttm4pCDpRmjkzM2Fipd8sZkslm9ou98iBLOW7t7VPYKy7MwlnSFiXSGE2du3kkLTvujBANWC7vP2haKIWpofLjALMpMTupNmVeR5VmESPpeZ10Yg0X9DkhYBJkcq0m16gO+nuxqIoGuaK3q6xSPP6pXCEEOLz4hotVpg3teUYL+rPnDEhvgwjHaBBRhhl5/vkTgJaqYuvmPIlaD6cOIqmToReaPYc54nEkygn02REQY1yeAoQSmkH6Ko6KFQum8hFBMt1R/qndksBcV+T9ZOKdSbOLoZ+ZZzUsS8SheVna5ITRcsWNIV0cbAk4=

deploy:
  provider: s3
  access_key_id: AKIAIBXD77AXW62WB2NA
  secret_access_key:
    secure: TMb/wV1jj8/BeePShLimb9abrkgQAxYb/0KgWHmpTO6rZ2BYnXQovXDONK7mLDb7QOFo5ZPLjmsw+GQ5EsOqbTfNHa/+PYvwaEdNhWuhlKTmych15y1hHrVc1Eub6SejYBXIyEr6TEGDK5W6+VeRbIgiPF2gJrWBW6H6fMShfEPrJ9B25rFovND8v9LjGXp6roly726/U7d63+gDfOMIGhd/nXHqig5qZGEsOkgihmFqquFwyhj5LNHFMsX3QW8Q0fkXOScVtVFM/YSfMc1uVDP05FIfxXf393rbOJmUGzcWxNzl3XUTxMUPVYvBPKbeLVWkpjFsaBujOCDWmwmrBNwh2G8XlS8s3MGCU5mufj788NaN385HXU6xrIlKDuKkV5yilwtSaP9+IUQfzwAF4IX9W6B+pawujwnAPnOPJj4vdukoJLB2MJaNJw+EXG+8INUrcBL6TQvNZMREg3NcguJXy22RZPP3zIB2ZcyB3hoEiYIofBEFZL4e4TMTGvqG11zH2hVnz4i/DKBSpaQ6EZ3i2zhHZusrr6nIrIAzsXuL8mKV2XMHYbEuUbgd5/qiFOTV7b1dYCn1FCsmXbdjtdWizaB6PBnBDky2Z7qu/91YmPxd2rU/QsdMU/rJSKv69i85jlq5B1oqL6ieh8YWDvSQyRAcAuXVyhx19w1z5qc=
  bucket: franz-travis
  region: eu-central-1
  local_dir: out
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true

env:
  global:
  - secure: BbImFf84jiAKMYhjwXKupKBjEvdftFcD1jnClY1IjY7l17Wk38XVwhLuI0dNSKC0cEC+acHqJEIyvr0qXcPDBnOhTyaDFtIeExQ9lCksxK/MHVFq6UGN5ogEggUZUkcf88Sk3CpaIiQCmPzifZmTbqEYxdcmeDhfthRvoSWYy/xV0hZyeIvXP4YNXdLrqh8bzBzv9FlDWtfV4UoHLPg69P2pWrR6WXvQiMpy1OKpJnShoaS5RjIGK/o4Qo+XswBPpUWxfH06yijCNeqljQvYJyRHnsbwUJY/+3EJwoxSGs2v6Ca5MPjLC4+GeLJOou6IbITA1yO4/tTVs5kr8dD31f75qYF4yAtLDjR6E+HRHguRHV6g3G8xNS9lv2MuV2lLtnSifHuMOtJWDXj2wFqlhUmMbBaA/Y3GHaIWji+ARZ1/b6c/vX2u3Pfw7rc4usOyQo2wwIeDfkz7fbed9QwanaMjNvrQN46/wF/IIpSAR99h5vtjU08yPqOiEbJAvrufjUykW6mAUiJCcBk2aKwbJl7f7kEIwhLVfnxy6ywPwvYQgelMpq0rmeWdN9KV9QFM8PQXOZ+um5eG56SJ4cENAqDiiEYwf4gAqiEXTPsqRUryj6LuiGs0NbYodP6Kk5shiw3BNsFpqtKxBlNZxrH3/cSCtYzemDdFCvKS/8rf+7w=
  - secure: K9rF36hqDZMZw2cl7R7HqnurWX6YSgHtjK+u9rfaxzi2K87f30mSsYFWSh02X8WA9hZ1Ev5A1qOzMkCsKRCGirrJpAcgXTi0nMq/qJZiKHqmchoC0TrsBTIG35t3ldfhGgyEQeFp/xDV2GoiLsGPPTiK6or+9ydvwxr2YLHmjCyDoWKlPVzwebnqynALRF1keVPnLM6erH+UYRxbF9elCo+3Xif5wTZo3/maZ8RTNy+ofDPT2GhsFXkIwo0eaI2aWHxqyppt4tTzXbL7+kdhnXCkm6hzPlh7VKFBjLV5khkbDnotYLlQjwdzq1mG9cjWnUZbu3JoRf7uM36MJ/n3bcYc2+95+JFDw5sFFeCVlXyiJsMjP1c8k3PPEZ/qqamg9DBvpYg4F4FoHR929eeNSp3AdN8lK5OoEOFlcizsvQ0v/17laV1/kkbVpwy0PzStbDlbu3G4i4ru3z+RiFycar1pl0j6jJeCSWthENq+TwrwNstG7PQnEKmIq7WGQEai/AnIK7x1fEis1754KubR+QGgBxg6qnR9Wrb3Zxwvy1NhygC6P9qP/M5cYdc7L49t9es3xFTtdqle07xufPH/aQxl6MhKYKVY6nAlYTOxjqGTZErUXFA+rdRotHIzX8G8tWc4CwBYu2YvAc8ua02YbeXCuyOuPDVWwEQdzQu2VUc=
  - secure: R5I0YyyLhvjNNZ3QbhSVntIyfs6tSWqSMKPX50aQX0pop5mhElZGiUgrjHmybNrEWhtPY74FdtVzY7SZBRJ0z9djwPmY1hxjHvl8JOdVtyvo2B4Mo6yiJ30UzjOVCDI+xx8iqv0XzyMHaWDX11L+YarufGXSsRXDvURzOQkeBQ6XPomHOXdTqwDBKrbQflk1xAG4nnfZl8hZ+wQVuZigrfHpmeJx25D2D8JxwcJam/VhmvG23IKOamgE4Roi0xvsewT19AFAj6/z94YgT24O7UMEYxfQ947FJZImENt4qBTIEHQybmL4uXMxohPhpMNVcJL9yIfjQJVIuIDVRd9cW4ESlxxXLHdK0ZMSnKb6jSIEvoT3jQDwl5LSqopRnryHsNLhe/sN9b6qbL4BqPM1L41PUe64Q4U8fZzu0ZfNge4urqewSr9IKZpOlPK3k1A9e8rp/2bSHmpIEC9nFu+BJVCIMNm3m6ur3Nf4UGBWNxHLeh9GG6xa1MnWpktUrRT2SlADMi3ffV0OlCINMRGyCE7g7itnGm4d2nOxuQtxC+CC1TDaS1sww/N5Xth5aoIzDsd9FI4dR4FtrbBtBOwKdr+Ag3LYYHLjqRItYiuWHFZ/eZ/CcBg2ial9Rj+JJuVLhf6fC/29x0cGTKz2Pb4hlGqs/bV0XegotQ7muBrICaI=
