language: node_js

before_script:
- yarn add global gulp-cli@1.2.2
- yarn add global gulpjs/gulp#4.0
- yarn add global node-sass
- yarn install

script:
- yarn lint
- yarn build

node_js:
- '7'

os: osx

osx_image: xcode8.3

cache: yarn

notifications:
  email: false
  slack:
    secure: eVryP5RSaK0zOTZGx5zxt64dFzp0QT95XdX4R6XOgw7WUXbAatO4pLRrJzxi+Ur5bQDPD4hroewAJ77gGSUasFHVb+seiCFwHaszQtq8m8rVh9P/tUG+JP7U8gcOR7nTVhNw5HF5DUO8j8iMqpdvievBQ1KbnYALwcQQj1W/T+UbFCyWYaa3VpJCdOUnbJadeMKcMws9aSStZcQ3wUIvDG3YbpNH02lU3vjU80Y0dMFlGfm8DI9h7pdXQM4VQdyAdtf2fSYV1OMRE7lU2bJP6BX5qcq3+oYty554owVLdF4yBmaFKcB/OOqreOV/GyKLVhZtJIGg00+xTORVBl+1nyO1RsIyCd9FwvwvCRk/f/Nb5j9o96TqIRdssXM3yptVV7cXP0Qwt99BVjice4cb6fXMnu1g9e7kR4K5o/lLijw2CfGcneETj/jh479efCrf4CTX2wRZ6dggE6XQ2zxk6nVz+Y/8HrK9QrAsUlbZcJjCx4oDFCuubP6yccc3NCOd54SdFf0STVt4Yq+63eX8yJhEC2iiVrr9UHrS/9mVxG+pojhyZgOPNYeEvx99nozy2Z9txYrsB9dbqTNmNRVuZozuM8HRDL35l50ZvBALQkj0iqpIGjVEfE3+yc08Idk7Y+cLkuModxtBT4r3cT9EkI62CkhglYMFrR+wVz3HfyA=

deploy:
  provider: s3
  access_key_id: AKIAI6ZWIP2OWZUCXIGA
  secret_access_key:
    secure: HB77zpnMRC0yPa0V+q8H+JzgVFC89OBFZeNdLkZ7jBOGJL2MubgrV2+Qz1JS23972uYLWhY+f0cCc/fbWA19RJ8Bj7MYP/QeSe+psI4F6ge1EjfPzMKkkEtdsUJuV5puEoRQai9sh/tjOsTSyEbwQhyLD/SUlnyimdxsFRujoltyyCqfaHMYU8N9EmS+VIgRXzTOIfQ0u1GcB7E9cnOEdjYWAvUW7vklJ4esVwmPt11KCM+JbOhdenTSr+JaBxopALWs2a3a+wpJ4rsrZlsyAisiOzvgqDlmWRYFyzmIHp0tueiMz5L7sYL/HqgDUkUMVqa3LYzc3iRLab2sm+ukYyNxNK6sNvcWj/gQtSncy5PJ9ZKga1t3CGaze4tGCdAaQdo5lPDywi3Oi3cH7q2gpuubZ5ImgAGkbEDiacZsJR5qRhUZ9gx3gVgSrhKfIx/1lPxsZ8p2LGYL84HKgENOIRWthnzkIgo8xP3ykOun5FihZ8pt3EoJG9NF08YBkMG1FOWxnI2teXb3FZSETt767Qe5DW27WE52daiExO5klgg+dX7ud9f/3G5Fv0auOdAKzj8kM6oyi3YX97nRpoKt/VmeoebUbK6D4WV2lhPLV37xqg1Ak8VfESD8NHsIDm8yS/sIDIQUSsIBDEEt0yBGggkJ/jOmgfk2RPPz2Wy2ClM=
  bucket: franz-travis
  region: eu-central-1
  local_dir: out
  upload-dir: "$TRAVIS_BUILD_NUMBER"
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true

env:
  global:
  - secure: QQHW81r1ozzT7SvrR+t0szpcqFau4AI14wduZwOUWQk7GxK54Spkp75ebGd1EM1AwNS97DLg8FFNzxEWSoTzn8kDvLQ4UXrQBtqYSGscCHnEFWcReFniYd9H1FRjjVwhgU/9R0nY+eZeArC/6Y4L6ZEQ3leHfG2Wq5wCGpmMhC5ngYN4YXa6KHLj9ZGELqE6nniPcouTtIDbTl4EU0rpwIpEFGGakGZCzz+BLF9ZVYXyEOFHMr1sqzYFngtV5Of3qrEqFW+ea1tDgIPvt1MIkQOASR3X/s8K1LHyj0UugOpUyCgAHtJDDWJa/HGcb86rPdYRUgXAj5CSiGJgsiGv6eDm7Sua1QHaEMZ9YfHB0IuafzOY5cbSEubCuJlnREB7EvMF6nvFMKeRNoEmqbts8wXTzgh3LkeR2LfMedqNQh0ianG5QwXQxtmaoQ7cw2eQEMADe7AbIbJv6El91p/vEHIO7ESNPsYo8vTEannlKswi//VO2Q3iPnHx0VSqIlbMJOkG/624j7aXxsqvufDrWXIOSz0A7kZz4ri2MevGujejeip0k3y6ofZk7eeUmQew4LtzQZiiqJnrOM9DSJ8ziuNplFMNeGILYLx2Ai9v8UGKxr7GhKURlTaQxeqYiT5W0LiDDuzfozCXXhLKdfoGiohi5mUJBjFeGFPv69ME+m4=
  - secure: ZBRC0KzerbbUH1WgQq8YYcPiKXWoIifTijP9XfLBM8u+IWnULxyFciFSsFR7g8ck1Tby5ajsqk4Me7OgxHdOn9Ds8xfvGAgP2a1V3qtUcEGUyKjpERc03/n6KTcJdZL2H9Ir1YqnA59UZJFghemannEwNjHUjXIwCQqOij89D4CkMBXI7g52dpYsEiG97fHRh2thI/I9f7x9PuAYKnLC9Zk8bBolIBJZ37/prAQosZH+ZhoqcrZYj7SfuZ7rceZQ7AESfF7Y+P/s1y7k8cbOGvy/Y36U3+M1Iz0PraEyr3kQ5hU1GRgg5IdJzD0HqdjXd42CzH9NlyNwNzehPhgxBvhYdPPhgMX8P5SViD4zjQ7EAn0RzLydp4VuihLmAJhy6aMAZ4VAEy8pucvC1tlfZw/3zuMfOyjThcx1Vk2Db9+ZSP86HI3DAMUpg3cEnZo01Mx498bKJzMR/9JgP2AZ8IWefxin3k2yi3tcwhUB+iDfMJGzeLDMBIMltqM7hz3lwE0hfYkT3bEZujHCAVW2E6+gzdB/IiNbX9iRrYBG23dwWkCWgA55eAu3Rzv5fqZD0PX7/3XjdlFVESnqiJecgu/cXYvsV/eZfXdPi3FuxrpGj4QN9CuHuHoBBlHbOnLur/65iqzgDMdmd33G2VLAGUDwGZK/BmvKD5F8xmCqtYU=
  - secure: u5RaqOpoHfnYbKYOzBG9r+6y6wnLTcU49QHgJC2LdXsTBCe5lms4DjxSS5kVqlkLMo8u/Lsd3dORcC0/E4hKaphGgKqHrdPBaJDADMqhY1xD5OwoZbFu8+BKAH0W1cNdr0ZXLFpHQxGcXLg6ofbrZbWg9fYQ5g7Do2ypOXWhoCxsbtF1sOYCyXeOL/O8EqMG0Hif3QOqnpCrdMTL/RjHzc/c6s2sIbsNd8ca4RLHwMZ3yDl1kEePRsB5vR3ZACd7hEDWCeQ9baSmaaAgVudIB6lGyRZgNFTcu5FXyAGfnNQkakHHWtWKXbYEppValTKUGB6t7UmkUw47UsP2t7tTcJG5KpIh5HbN0GoTsabO/OcjIv3cfDIEdsgM44ZoemE0ajdQTLnatVIlTuL1o30IoiIeaBdQUoVJ8TUP41UT8sYYBV7p1ctQluoQ00I3IjmNKnoVkcG/MvVAfk2E50gDswFfH9g5ZOl+vebSV1jYnZVUSdFxqjPEQBL6Ss4dKYpJM9roJstYq27Nm85vUzUd1a50ntdxJyebDEmyc5pGeMM0mS9MwiMAMTEHwvntgv/YBT6ZWyqGMpzIjgDHYVmbICScgutvQ/d+YjheAyTwuDQzvWMCsvgBF7FubPePveQgjZP+QwlyoX0GPfnkmMjRerzyB0ssdSRnVgsdmlhXcuc=
