environment:
  GH_TOKEN:
    secure: LiO1Z/i16UV5YyElROSUykQqpJowSMK86I7Nw4G/NMa0q5yNA7EsUqEiJUL+OG01
  CSC_LINK:
    secure: NEYFWgUIAB//y2GR4AJOaegwuNjkxyNsdDf5A40dYovebTUsnIB5k4GCbU3I6JKW9iwH2ldU7Z+QawfyFerNgw==
  CSC_KEY_PASSWORD:
    secure: t8ypNTPKTmvRfd3hHA4aMOtC5KOFqOw3AsKhpU7140Q=

version: 5.0.1.{build}

image: Visual Studio 2019

install:
  - ps: Install-Product node 16
  - npx lerna bootstrap -- --legacy-peer-deps

cache:
 - '%APPDATA%\npm-cache'

before_build:
  - npm run test

build_script:
  - npm run build

artifacts:
  - path: out\*.exe
  - path: out\*.yml

branches:
  except:
    - i18n
