environment:
  GH_TOKEN:
    secure: LiO1Z/i16UV5YyElROSUykQqpJowSMK86I7Nw4G/NMa0q5yNA7EsUqEiJUL+OG01
  CSC_LINK:
    secure: NEYFWgUIAB//y2GR4AJOaegwuNjkxyNsdDf5A40dYovebTUsnIB5k4GCbU3I6JKW9iwH2ldU7Z+QawfyFerNgw==
  CSC_KEY_PASSWORD:
    secure: t8ypNTPKTmvRfd3hHA4aMOtC5KOFqOw3AsKhpU7140Q=

version: 5.0.0.{build}

configuration:
  - Default
  - AppX-WindowsStore
  - AppX-Testing

install:
  # - ps: $version = Get-Content .\.nvmrc -Raw
  - ps: Install-Product node 10
  - npx lerna bootstrap

cache:
 - '%APPDATA%\npm-cache'

before_build:
  - npm run lint
  - npx gulp build

artifacts:
  - path: out\*.exe
  - path: out\*.appx
  - path: out\*.yml

for:
  # default build / .exe / signed
  - matrix:
      only:
        - configuration: Default
    build_script:
      - npx electron-builder --win -p onTag

  # Windows Store build / .appx / unsigned
  - matrix:
      only:
        - configuration: AppX-WindowsStore
    skip_non_tags: true
    environment:
      CSC_LINK: ""
    build_script:
      - npx electron-builder --win --config=./electron-builder-appx.yml -p onTag

  # Windows Store test build / .appx / signed
  - matrix:
      only:
        - configuration: AppX-Testing
    build_script:
      - npx electron-builder --win --config=./electron-builder-appx.yml -p never
