name: Build/release

on: push

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npx lerna bootstrap 
      - run: npm run build:packages
      - run: npm run build:sources
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/


  package:
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Download build artifact
        uses: actions/download-artifact@v3

      - name: Windows setup preps
        run: npm config set python python2.7
        if: ${{ matrix.os == 'windows-latest' }}

      - run: npm install

      - name: Package binary
        run: npm run bundle

      - name: Uploading build artifact
        uses: actions/upload-artifact@v3
        with:
          path: out/*

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: out
          destination_dir: ${GITHUB_RUN_NUMBER}

    env:
      GH_TOKEN: ${{ secrets.github_token }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        